### ISSUE TITLE
concatenation error

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/doc_curation#11]
```
Traceback (most recent call last):
  File "auto_ocr.py", line 7, in <module>
    pdf.split_and_ocr_on_drive(pdf_file, key_file)
  File "/home/dhaval/.local/lib/python3.6/site-packages/doc_curation/pdf.py", line 63, in split_and_ocr_on_drive
    file_helper.concatenate_files(input_path_list=ocr_segments, output_path=final_ocr_path)
  File "/usr/local/lib/python3.6/dist-packages/curation_utils/file_helper.py", line 6, in concatenate_files
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by drdhaval2785** [comment]
The OCRed texts show proper data.
Their concatenation seems to have some issue. 
Ubuntu based bodhi linux distro. python 3.6.9

**Comment by vvasuki** [comment]
Thanks for the report. Updated curation_utils.

Please use `sudo pip install git+https://github.com/sanskrit-coders/curation_utils/@master -U` to get the latest code. Then, if you still get an error, I am guessing it must be something very simple - just debug and submit a fix to https://github.com/sanskrit-coders/curation_utils

**Comment by drdhaval2785** [comment]
`os.path.dirname` gave empty string when the script was run from the folder where the PDF is also situated.
`os.path.dirname(os.path.abspath(output_path)` made it to work with either the full name or short name of input file.
