### ISSUE TITLE
manually override ghostscript compression

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/doc_curation#12]
In majority cases, the PDF are just images.
In that case, the compression seems to take way too much time.
If we can have a flag `comress=True` by default, which can be changed to `compress=False` if we do not want the compression to work, it will save a lot of time.

**Comment by drdhaval2785** [comment]
I understand. There is a submodule which is not cloned because it is in your repository and not in organization's repository
```
fatal: clone of 'git@github.com:vvasuki/Stylesheets.git' into submodule path '/tmp/pip-req-build-g1r07__3/doc_curation/tei_xsl' failed
```

**Comment by vvasuki** [comment]
Real problem there is that submodule url is ssh, not https. Fixed now (and transferred the repo as well.)

**Comment by drdhaval2785** [comment]
Closing this for now. If any problem comes up, will notify.
