### ISSUE TITLE
HttpError 500 for specific PDF

### ISSUE THREAD

**Issue by lalitaalaalitah** [sanskrit-coders/doc_curation#16]
I'm getting `<HttpError 500 when requesting https://www.googleapis.com/upload/drive/v3/files?alt=json&uploadType=resumable returned "Internal Error">` for specific PDF.
One of them is about 2 GB in size. I used split of 10 pages and then 5 pages. It gives same output and not even a single split PDF is OCR-ed.
There is another file which is 1.38 GB in size. The code works for up to 85 pages and then throws same error. I've tried multiple times.
I tried to compress a PDF and it did 0% compression with every option and then since the size of all split PDF was more than 1 GB, it returned same error.
Please, suggest some solution for this size limit.

**Comment by vvasuki** [comment]
compresshion_power इति परिवर्त्य पश्यतु, यथा -

```
doc_curation.pdf.drive_ocr.split_and_ocr_on_drive(pdf_path="/home/vvasuki/Documents/books/granthasangrahaH/purANam/mahAbhAratam_gItA-press/mahabharata01ramauoft.pdf", small_pdf_pages=5, start_page=336, pdf_compression_power=2, detext=False)
```

अन्यथा - 

```
doc_curation.pdf.drive_ocr.split_to_images_and_ocr(pdf_path="/home/vvasuki/Documents/books/granthasangrahaH/purANam/mahAbhAratam_gItA-press/mahabharata01ramauoft.pdf")
```
इति प्रयतताम्।

**Comment by lalitaalaalitah** [comment]
There is not module called `drive_ocr` either in `doc_curation` or `doc_curation.pdf`.
```
>>> dir(doc_curation)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'codecs', 'logging']
>>> from doc_curation import pdf
>>> dir(pdf)
['Path', 'Pdf', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_get_ocr_dir', 'compress_with_gs', 'detext_via_jpg', 'detext_via_ps', 'detext_with_pdfimages', 'doc_curation', 'dump_images', 'errno', 'file_helper', 'handler', 'images_to_pdf', 'list_helper', 'logging', 'os', 'shutil', 'split_and_ocr_all', 'split_and_ocr_on_drive', 'split_into_small_pdfs', 'subprocess', 'time']
```
The module `pdf.split_and_ocr_on_drive` was giving that error. Any hint about where the image ocr module is located?

**Comment by vvasuki** [comment]
Maybe you're using some old version of the code? Please install the latest as shown in https://github.com/sanskrit-coders/doc_curation .

**Comment by lalitaalaalitah** [comment]
That's correct. I was on `doc-curation==0.1.2`. Just updated to `doc-curation==0.1.3`.
The new process gives `[Errno 24] Too many open files`. This is known problem with PIL(assuming you are using Pillow.). I think that you may have to add some solution for the same.

**Comment by vvasuki** [comment]
I have not tried or tested split_to_images_and_ocr - I just added it on a whim - so it will be good if you can contribute a fix.

Did the compression_power trick not work?

PS : Best practice for this repo is install directly from the git repo (as shown in the  https://github.com/sanskrit-coders/doc_curation ) - as I don't always update pypi when I update git.

**Comment by lalitaalaalitah** [comment]
compression somehow manages to create 1 GB file from 200 MB original PDF, so it fails in similar way.
I always install with pip as shown  in README here.

The solution which I've implemented for now is to split a PDF to small_pdf with 25 pages each, then considering each samll_pdf as pdf_path split and ocr with chunks of 5 pages. Appears to work. The problem is that I've to implement a solution of combining OCR of each small_pdf to one txt at end.
BTW, for DLI PDF downloaded with barcode page, the compression doesn't help and OCR comes blank. So, I've to create a function to extract and delete the 1st and other pages and then compile PDF and then do all process.

**Comment by vvasuki** [comment]
Can you post the code you're using?

**Comment by lalitaalaalitah** [comment]
check this:
[https://github.com/lalitaalaalitah/doc_curation/blob/master/Script_To_Use_DriveOCR/v1_run_drive_ocr_for_a_pdf_or_PDFdir.py](https://github.com/lalitaalaalitah/doc_curation/blob/master/Script_To_Use_DriveOCR/v1_run_drive_ocr_for_a_pdf_or_PDFdir.py)

**Comment by vvasuki** [comment]
PS: plz consider contributing the text to https://github.com/sanskrit/raw_etexts
