### ISSUE TITLE
Rare books in GOI websites

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-coders/doc_curation#19]
The below is from @lalitaalaalitah 

Please, check this website. :
https://www.indianculture.gov.in/rarebooks?search_api_fulltext=&page=490
Their scan quality is very good.

If you could find a way to extract URL, it will be nice.

I downloaded one with cURL by sending exact URL and headers.
I have observed that we have to open dedicated page for each PDF(which downloads the PDF in a container, and doesn't allow saving and copying, etc.). Watching network tab in web developer of Firefox, etc, you can get the URL as cURL downloadable arguments.
I hope you will be able to either create/help me create a tool for download.

**Comment by lalitaalaalitah** [comment]
I've a script now. I'll publish soon after cleaning and polishing it.

**Comment by lalitaalaalitah** [comment]
The repository is here : https://github.com/lalitaalaalitah/Scrape_IndianCulture.Gov.In_Release
Mind that Rarebooks are more than 800 GB and Manuscript about 140 GB in size. eBooks are not yet calculated.

**Comment by vvasuki** [comment]
Super!

**Comment by vvasuki** [comment]
Do you mind sharing your contact number so that I can put you in touch with people who can save this collection to archive.org for easier access?

**Comment by lalitaalaalitah** [comment]
I can create a script to upload all data. If you have suggestion, please share. It will make things easy.

**Comment by vvasuki** [comment]
Chetan pandey of egangotri pointed me to this - https://www.youtube.com/watch?v=1HBsc4UlxnY . Please use it or something similar.

**Comment by lalitaalaalitah** [comment]
There is an official python tool for upload.
I'll use that.
I already use it as a part of my custom download tool.
https://github.com/jjjake/internetarchive

BTW, I don't know if uploading to the archive will be considered illegal or
not.


*श्रीमल्ललितालालितः*www.lalitaalaalitah.com
