### ISSUE TITLE
Where's the source code for curation_utils?

### ISSUE THREAD

**Issue by lokeshh** [sanskrit-coders/doc_curation#2]

**Comment by vvasuki** [comment]
Look within https://github.com/sanskrit-coders

**Comment by lokeshh** [comment]
@vvasuki There's no repo with the name 'curation_utils' there. The source code like [here](https://pypi.org/project/curation-utils/) refers to https://github.com/sanskrit-coders/curation_utils which is broken.

**Comment by vvasuki** [comment]
Why do you say it's broken? https://github.com/sanskrit-coders/curation_utils has the code.

**Comment by lokeshh** [comment]
![Screenshot_20200426-072124_Chrome](https://user-images.githubusercontent.com/7677524/80295233-c648ff80-878e-11ea-8f2e-aaa8177c6ccb.png)

**Comment by vvasuki** [comment]
Oh! I had unwitting made the repo private. Fixed now.
